- README.md
- benchmarks/bench_test.go
- iavl_node.go
- iavl_nodedb.go
- iavl_orphaning_tree.go
- iavl_path.go
- iavl_proof.go
- iavl_proof_key.go
- iavl_proof_range.go
- iavl_test.go
- iavl_testutils_test.go
- iavl_tree.go
- iavl_tree_dump_test.go
- iavl_tree_fuzz_test.go
- iavl_tree_test.go
- iavl_versioned_tree.go
The historical queries feature is separated in two new datatypes: `VersionedTree` and `orphaningTree`.
The former keeps track of multiple of the later, and is the API for working with historical queries. The later is not exposed, and is a wrapper around `IAVLTree` which has the additional feature of keeping track of orphaned nodes.
This implementation of historical queries allows for gaps in history: it's possible to delete intermediary versions. At all times, we attempt to keep the minimal set of orphans required, since version `N` might still be depending on nodes from multiple versions `N - M`.
There is currently no automatic pruning of the tree, since the pruning strategy is to be determined by the user of the tree, ex: keep every 10 trees on disk (10, 20, 30...), or every 100 trees …
> Historical queries

- basic_test.go
- benchmarks/bench_test.go
- node.go
- nodedb.go
- orphaning_tree.go
- proof.go
- proof_key.go
- proof_key_test.go
- proof_range.go
- proof_test.go
- testutils_test.go
- tree.go
- tree_fuzz_test.go
- tree_test.go
- versioned_tree.go
This changes the API for saving versions from:
```
SaveVersion(version int64) (hash []byte, err error)
```
to
```
SaveVersion() (hash []byte, version int64, err error)
```
Where the new `SaveVersion` auto-increments the version, starting from 1.
> Auto-increment version on save

- .gitignore
- basic_test.go
- logger.go
- node.go
- nodedb.go
- orphaning_tree.go
- proof.go
- proof_range.go
- tree.go
- tree_test.go
- versioned_tree.go
> Clone w/ version; Remove orphanIndex

- chunk.go
- chunk_test.go
- path.go
- proof.go
- proof_key.go
- proof_range.go
- serialize.go
- serialize_test.go
Since the structure of the tree (and thus the hash) is dependent on the insertion order of the keys,
we cannot simply dump all key/value pairs and restore them, if we wish to copy a tree from one node to the other (and maintain the root hash).
However, if we could determine an ordering of the key/value pairs, which would produce the current structure when loaded into an empty tree, we could then have a portable and efficient serialization format.
I came up with an interesting idea of constantly bisecting the tree and adding the leftmost leaf for each new section for which we have no node. Wrote test code and it seems to work. Please review it:
`serialize.go:StableSerialize`
Note, that this needs some more issues for production:
* For versioned tree the height is part of the hash... that …
> Provide stable serialization for IAVL tree

- chunk.go
- chunk_test.go
- node.go
- proof.go
- proof_key.go
- serialize.go
- serialize_test.go
Reverts tendermint/iavl#24
* The implementation is broken, since inner node versions are not always equal to the left-most leaf's version.
* Need to remove breadth-first serialization logic.
> Revert "Improve serializer"

- tree_test.go
- versioned_tree.go
This greatly simplifies use of this data structure as the backing
store for an ABCI application.
Closes tendermint/iavl#43.
> Return the latest version found on tree load.

- amino.go
- glide.lock
- glide.yaml
- node.go
- nodedb.go
- proof.go
- proof_key.go
- testutils_test.go
- wire.go
Use latest amino instead of go-wire (see #51)
WIP / Notes: After switching to amino e.g. `TestVersionedRandomTreeSmallKeys`
currently fails/panics (at least most of the times) with: 
panic: Error reading Node. bytes: [...] error: insufficient bytes decoding []byte of length [...]
`TestTreeKeyRangeProof` fails with "invalid proof"
> Switch from go-wire to go-amino

- basic_test.go
- node.go
With current code, if you call Tree.IterateRange with a range to the left of the left most leaf node, the function will return that first leaf node anyway. Fix checks start and end before returning leaf nodes from node.traverseInRange.
See also: https://github.com/cosmos/cosmos-sdk/pull/931#issuecomment-400884242
> IterateRange bugfix

- proof_range.go
For an unknown reason, this line is causing a linting error in the sdk. (Even though we have it set to ignore the vendor directories, and it succesfully ignores all other linting errors in other vendor directories)
> Fix linting error on the sdk

- CHANGELOG.md
- Gopkg.lock
- Gopkg.toml
This is done to remove the need for an override constraint for tendermint
in the sdk.
Closes #90
> dep: Change tendermint dep to be ^v0.22.0

- CHANGELOG.md
- key_format.go
- key_format_test.go
- nodedb.go
- nodedb_test.go
- proof_test.go
- testutils_test.go
- tree_test.go
This fixes #104 by introducing `KeyFormat` that uses a fixed-width key format over the full 8 bytes provided by int64 versions in orphan, and root keys. It also relies on the fixed width format to provide more efficient code for formatting into and scanning values from keys.
As a result of this it seems to lead to a ~10% speedup in `BenchmarkTreeLoadAndDelete` by avoiding the relatively expensive `fmt.Sprintf` and `fmt.Sscanf` functions, see below.
```shell
go test -bench=.
goos: linux
goarch: amd64
pkg: github.com/tendermint/iavl
BenchmarkNodeKey-8                 	 5000000	       316 ns/op
BenchmarkOrphanKey-8               	 2000000	       613 ns/op
ok, starting
BenchmarkImmutableAvlTreeMemDB-8   	200	   5783362 ns/op	 1104190 B/op	   22488 allocs/op …
```
> Use 8 bytes to store int64 components of database keys 

- CHANGELOG.md
- version.go
Bump version and update change-log
> Prep Release 0.11.0

- CHANGELOG.md
- basic_test.go
- proof.go
- proof_iavl_absence.go
- proof_iavl_value.go
- proof_range.go
- proof_test.go
Depends on: https://github.com/tendermint/tendermint/pull/2298
> General Merkle Proof

- CHANGELOG.md
- Gopkg.lock
- Gopkg.toml
- nodedb.go
- version.go
See https://github.com/tendermint/tendermint/pull/2913
> R4R: Use new tendermint/libs/db.DB.ReverseIterator API

- CHANGELOG.md
- Gopkg.lock
- Gopkg.toml
- version.go
update to tendermint v0.30 and bump version to 0.12.1 (for immediate release)
Dependency to  tendermint v0.27.0-dev1 was causing some inconvenience when developing an app which has the sdk and iavl as a dependency.
cc @alessio
> update tendermint dependency to v0.30

- Gopkg.lock
- Gopkg.toml
- nodedb.go
This one is related to https://github.com/tendermint/tendermint/pull/3397, that writebatch should be closed if no longer needed. This one could be the major part of memory leaking when use CLevelDB, since it's in the hot loop.
> close batch after write in nodedb

- mutable_tree.go
- tree_test.go
Implement lazy loading of a given version.
ref: https://github.com/cosmos/cosmos-sdk/issues/4326
> Implement LazyLoadVersion

- benchmarks/results/169/Rickys-MBP-0.12.4-3-ge247ad9-results.txt
- node.go
- node_test.go
- nodedb.go
pre-calculate the buffer size and allocate before serializing the node.
```
BenchmarkNode_aminoSize-12             	200000000	         8.63 ns/op	       0 B/op	       0 allocs/op
BenchmarkNode_WriteBytes-12            	 5000000	       371 ns/op	     368 B/op	       9 allocs/op
BenchmarkNode_WriteBytesPrealloc-12    	 5000000	       322 ns/op	     224 B/op	       8 allocs/op
```
note this benchmark needs another PR from go-amino which accelerates the VarintSize() method
https://github.com/tendermint/go-amino/pull/282/files
> preallocate memory for node serialization when SaveNode

- benchmarks/bench_test.go
- benchmarks/results/168/Rickys-MBP-0.12.4-4-g494d60b-result.txt
- mutable_tree.go
- mutable_tree_test.go
estimate and pre-allocate the space for the orphaned nodes. It really matters when the tree become higher and higher and we have frequent set/remove operations.
benchmark
```
before:
BenchmarkMutableTree_Set-12    	  200000	      8845 ns/op	    6359 B/op	      65 allocs/op
after:
BenchmarkMutableTree_Set-12    	  300000	      5339 ns/op	    4604 B/op	      25 allocs/op
```
> pre-allocate memory for collecting orphan nodes

- mutable_tree.go
- tree_test.go
Details:
`Remove` operation will leave some orphans not collected. So these orphans would never be pruned from database. So many nodeDB operations would get the wrong result, like `traverse`, `traversePrefix`, `traverseNodes`, `size()`, etc.
1. Run the test code
```go
func TestMutableTree_Remove(t *testing.T) {
db := db.NewDB("test", db.MemDBBackend, "")
tree := NewMutableTree(db, 0)
tree.Set([]byte("k1"), []byte("v1"))
tree.Set([]byte("k2"), []byte("v1"))
tree.Set([]byte("k3"), []byte("v1"))
tree.Set([]byte("k4"), []byte("v1"))
tree.Set([]byte("k5"), []byte("v1"))
tree.SaveVersion()
tree.Remove([]byte("k5"))
require.Equal(t, 4, len(tree.orphans))
tree.SaveVersion()
}
```
The test will failed because the `Remove` only collect 3 orphans instead of the expected 4.
The tree looks like this …
> bugfix: orphans are not totally collected when Remove

- node.go
- proof.go
- proof_path.go
- proof_range.go
> export ProofLeafNode and ProofInnerNode

- CHANGELOG.md
- nodedb.go
When deleting orphans, an orphan node is deleted from the database while the database is being iterated over. This breaks the tm-db contract:
> CONTRACT: No writes may happen within a domain while an iterator exists over it.
This caused deadlocks and race conditions with the new [B-tree based MemDB](https://github.com/tendermint/tm-db/pull/53).
I believe this is an oversight, since all of the other related writes are batched in `snapshotBatch` or `recentBatch` instead of writing directly to the database. This change fixes the problem by batching the deletes instead. The tests pass, but I would like a confirmation from someone familiar with this logic.
> Fix concurrent database access when deleting orphans

- .github/workflows/ci.yml
- run ci when pushed to master
- run always for pull requests
- don't run ci when a branch is merely pushed to the repo
> ci: run on push to master

- export.go
To avoid races with IAVL pruning, the SDK must begin exports of all IAVL stores at the same time. Lowering the IAVL export buffer reduces the memory overhead of doing this, while still keeping it large enough to mitigate context switching penalties.
> export: reduce node buffer to 32

- .github/stale.yml
Stalebot had been turned on in the org settings but was missing a config file. 
No more!
> .github: configure stalebot

- README.md
Should really link to pkg.go.dev, the team is still working on a badge: https://github.com/golang/go/issues/36982
> README: add GoDoc badge

- doc.go
- immutable_tree.go
- mutable_tree.go
Fixes #241. I ran some tests with the Go race detector, and as far as I can tell these modifications are accurate - however, it's possible I have missed some edge cases.
> doc: specify concurrency characteristics

- CHANGELOG.md
- mutable_tree.go
- nodedb.go
- tree_test.go
LoadVersionForOverwriting should transit orphans to non-orphans for overwriting version and remove nodes, which become useless
Fixes https://github.com/tendermint/iavl/issues/141
> LoadVersionForOverwriting should transit orphans to non-orphans

- immutable_tree.go
- mutable_tree.go
> document byte slice immutability

- testutils_test.go
- tree_test.go
`TestVersionedTreeProofs` uses a tree with random pruning settings. This has a 12.5% chance to generate a tree which will delete versions that the test needs. The RNG defaults to `Seed(1)`, so this failure only happens if we change the sequence of tests relying on the RNG.
> test: fix random failure in TestVersionedTreeProofs

- mutable_tree.go
- nodedb.go
- tree_random_test.go
- tree_test.go
Fixes #273, caused by faulty orphan removal.
Branched off of #274, merge that first.
> fix LoadVersionForOverwriting data corruption

- docs/node/node.md
- encoding.go
- export_test.go
- node.go
- node_test.go
- nodedb.go
- proof.go
- testutils_test.go
- tree_test.go
Removes Amino and adds varint utility-functions instead, keeping the same serialized format. Partial fix for #242.
The last vestige of Amino is in the proof handling, namely `AbsenceOp` and `ValueOp`, which are structs encoded/decoded with Amino.
> remove Amino

- .github/workflows/lint.yml
CI currently fails since 1.27 is unsupported.
> lint: update golangci-lint to 1.29

- CHANGELOG.md
- mutable_tree.go
- mutable_tree_test.go
- nodedb.go
- options.go
> add InitialVersion option

- CHANGELOG.md
- basic_test.go
- immutable_tree.go
- mutable_tree.go
- node.go
- tree_test.go
Related to https://github.com/tendermint/tendermint/issues/5192, for RFC-6962 conformance.
> return hash for empty trees in Hash() and SaveVersion()

- CHANGELOG.md
- mutable_tree.go
- mutable_tree_test.go
- nodedb.go
- options.go
Requested in https://github.com/cosmos/cosmos-sdk/pull/7089#issuecomment-680877202.
I didn't add a `GetInitialVersion()`, since it's not clear whether this should return only the option or the _actual_ initial version that exists in a tree.
It might be cleaner to add `GetOptions()`, `SetOptions()`, and `UpdateOptions(func (o Options) Options)`, but we may not want all options to be mutable after construction.
CC @amaurymartiny
> add MutableTree.SetInitialVersion()

- CHANGELOG.md
- nodedb.go
- repair.go
on Go 1.x(x) all constants are ints by default which causing
build for 32bit machines to fail due to overflow
https://github.com/golang/go/issues/23086
> fix: constant overflow when compiling for 32bit machines

- CHANGELOG.md
Decided to squash all old RC releases, including the 0.14 line. Will leave them as-is on 0.14.x branch.
> changelog: release 0.15.0

- CHANGELOG.md
- encoding.go
> fix decodeBytes() integer overflow on 32-bit systems

- CHANGELOG.md
- encoding.go
- encoding_test.go
Fixes #339, again -- the previous fix had another overflow issue causing out of bounds errors. 🤦‍♂️ See issue for details.
Would appreciate thorough reviews to make sure this is solid.
> fix overflow-related out-of-bounds panic in decodeBytes()

- mutable_tree.go
Fixes #345. This would cause an error in any case, since the version does not exist, but it's better to catch it here.
> check version<0 in deleteVersion

- encoding_test.go
- proof_ics23.go
Noticed while auditing and profiling dependencies of cosmos-sdk, that
convertVarIntToBytes, while reusing already implemented code, it
was expensively creating a bytes.Buffer (40B on 64-bit architectures)
returning a result and discarding it, yet that code was called
3 times successively at least.
By reusing a byte array (not a slice, to ensure bounds checks
eliminations by the compiler), we are able to dramatically improve
performance, taking it from ~4µs down to 850ns (~4.5X reduction),
reduce allocations by >=~80% in every dimension:
```shell
$ benchstat before.txt after.txt
name             old time/op    new time/op    delta
ConvertLeafOp-8    3.90µs ± 1%    0.85µs ± 4%  -78.12%  (p=0.000 n=10+10)
name             old alloc/op   new alloc/op   delta
ConvertLeafOp-8    5.18kB ± 0% …
```
> convertVarIntToBytes: use reusable bytes array not expensive, discarded bytes.Buffer

- .github/workflows/docker.yml
Otherwise PRs from forks will fail, as they don't have access to Github secrets. Login is only needed to push images, and images aren't pushed for pull requests anyway.
> github: don't login to Docker Hub on pull requests

- mutable_tree.go
- mutable_tree_test.go
- nodedb.go
- proof_range.go
I recreate a PR again in place of https://github.com/cosmos/iavl/pull/358.
We can use LazyLoadVersion by #148.
But if we start app with LazyLoadVersion we cannot query app state by specific height because MutableTree.GetVersioned returns nil for other previous version after doing LazyLoadVersion.
Our nodes are facing a slow booting up problem because of the large app data, and I want to hear your opinion about whether we should modify the code like this.
> fix: Make GetVersioned() available after doing LazyLoadVersion

- .github/workflows/docker.yml
- CHANGELOG.md
- cmd/iaviewer/README.md
- cmd/iaviewer/main.go
The pr can support access to the data in the iavl tree of different modules of cosmos-sdk
In cosmos-sdk, the different modules under x/ use different iavl trees and are stored in the same leveldb (application.db). Different db prefixes are used to distinguish different modules, such as "s/k: gov/", "s/k:staking/", "s/k:evm/".
> add "prefix" arg to iaviewer

- key_format.go
- key_format_test.go
Closes: #417
If the segments is less than the layouts, the we don't need to allocate
full KeyFormat.length, just allocate enough memory to store the
segments.
```
name                                                old time/op    new time/op    delta
KeyFormat_KeyBytesOneSegment-8                        19.2ns ± 0%    16.4ns ± 1%  -14.62%  (p=0.000 n=9+10)
KeyFormat_KeyBytesThreeSegment-8                      25.6ns ± 0%    25.9ns ± 1%   +1.37%  (p=0.000 n=10+10)
KeyFormat_KeyBytesOneSegmentWithVariousLayouts-8      22.2ns ± 1%    16.4ns ± 0%  -26.14%  (p=0.000 n=10+8)
KeyFormat_KeyBytesThreeSegmentWithVariousLayouts-8    28.8ns ± 3%    28.7ns ± 0%     ~     (p=0.588 n=10+9)
name                                                old alloc/op   new alloc/op   delta …
```
> Make KeyBytes allocates less memory

- encoding.go
By using a sync.Pool to shared temporary buffer between calls.
```
name                             old time/op    new time/op    delta
Export-8                           7.88ms ± 2%    7.91ms ± 1%     ~     (p=0.356 n=9+10)
Import-8                           9.01ms ± 7%    8.88ms ± 1%     ~     (p=0.529 n=10+10)
Node_WriteBytes/NoPreAllocate-8     340ns ± 5%     235ns ± 5%  -30.80%  (p=0.000 n=10+10)
Node_WriteBytes/PreAllocate-8       274ns ± 5%     204ns ± 0%  -25.49%  (p=0.000 n=10+8)
name                             old alloc/op   new alloc/op   delta
Export-8                           3.74MB ± 0%    3.74MB ± 0%     ~     (p=0.796 n=10+10)
Import-8                           9.84MB ± 0%    9.05MB ± 0%   -7.98%  (p=0.000 n=10+10)
Node_WriteBytes/NoPreAllocate-8      368B ± 0%      320B …
```
> Reduce encodeVarint memory usage

- mutable_tree.go
- nodedb.go
close #427 
+ changed nodedb's mutex to RWMutex to allow Muti-Thread access
> add mutex to prevent concurrent map access

- nodedb.go
close #427 
#428  previous update contains wrong RWMutext update for nodedb cache, which leads https://github.com/cosmos/cosmos-sdk/pull/10040/checks?check_run_id=3475312162 issue.
To prevent concurrent read write map access in nodedb, this PR rollback RWMutex to normal Mutex.
> rollback nodeDB to use normal mutex

- .gitignore
- fast_node.go
- immutable_tree.go
- node.go
- nodedb.go
Created a new cache in `nodedb.go` that would be maintained for our newer `FastNode` structs and implemented the pieces necessary for changing `Get()` as per [this](https://github.com/cosmos/iavl/commit/75d6e9829a4a29b1b2fe02d0f2ead3dd7ae9388d#diff-f53b00cecfca17dc100d06e79d2ce350e3b92c09d33fe69d384feaba56d2aa40R154-R160)
> Refactor Get() to work with new faster cache

- encoding.go
- import.go
- proof.go
- proof_ics23_test.go
- testutils_test.go
- tree_dotgraph.go
> reuse buffer

- nodedb.go
- nodedb_test.go
- with_gcc_test.go
The prior code used a naive string concatenation
str += "..."
which is very slow and inefficient especially when iterating over
all the keys, but also it performed an unnecessary byteslice->string
conversion for all arguments inside (nodeDB).traverse* using
str += fmt.Sprintf("%s: %x\n", string(key), value)
notice the `string(key)` passed into fmt.Sprintf("%s"?
At bare minimum that code should just simply be:
str += fmt.Sprintf("%s: %x\n", key, value)
per https://twitter.com/orijtech/status/1462100381803102213?s=20
which saves a whole lot of cycles and RAM.
This change uses:
* (*bytes.Buffer) in combination with fmt.Fprintf
* A sync.Pool with (*bytes.Buffer) values to reuse buffers
and the results are profound:
```shell
$ benchstat before.txt after.txt
name          old time/op    new …
```
> perf: use a reusable bytes.Buffer to speed up MutableTree.String

- Makefile
- benchmarks/README.md
- benchmarks/bench_test.go
- benchmarks/setup/INSTALL_ROOT.sh
- benchmarks/setup/RUN_BENCHMARKS.sh
- Update to run benchmarks for all dbs (memdb, goleveldb, rocksdb, badgerdb) except boltdb.
- Update script to run the benchmarks with docker quickly. So its ok to run on local or dev machine.
Run the command below to install leveldb and rocksdb from source then run the benchmarks
replace (optional):
- `baabeetaa` with your repo username and 
- `fix-bencharks` with your branch.
```
docker run --rm -it ubuntu:16.04 /bin/bash -c \
"apt-get update && apt-get install -y curl && \
sh <(curl -s https://raw.githubusercontent.com/baabeetaa/iavl/fix-bencharks/benchmarks/setup/INSTALL_ROOT.sh) && \
sh <(curl -s https://raw.githubusercontent.com/baabeetaa/iavl/fix-bencharks/benchmarks/setup/RUN_BENCHMARKS.sh) fix-bencharks baabeetaa && \
cat ~/iavl/results.txt"
```
output:
```
➜  ~ docker run --rm …
```
> benchmark all dbs 

- benchmarks/bench_test.go
Closes #512
Fixes a slow query benchmarks using the wrong tree and causing `make bench` to fail
> fix: make slow query benchmarks use correct tree

- CHANGELOG.md
- mutable_tree.go
- mutable_tree_test.go
> fix: MutableTree.Get

- Makefile
In benchmarks we were running tests, which should be run separately
Moreover:
+ cleaned up makefile to remove not existing benchmark expressions
> make: don't run tests on benchmark

- CHANGELOG.md
- cache/cache.go
- cmd/iaviewer/main.go
- internal/bytes/bytes.go
- internal/bytes/string.go
- internal/bytes/string_test.go
- mutable_tree.go
- nodedb.go
- tree_dotgraph.go
- unsafe.go
- unsaved_fast_iterator.go
Avoid unnecessary allocation by using fast unsafe bytes -> string conversion
Notes:
+ I didn't add conversions to the tests - I'm planning other PR there to cleanup key / values repetitions.
> perf: use fast unsafe bytes->string convertion

- .golangci.yml
* removes gofmt and goimports in favor of gofumpt
* enables errcheck
> golangci-lint configuration

- benchmarks/bench_test.go
Only log to error log iff the -v flag is set, this prevents spammy logs and burning unnecessary time and logs.
Fixes #552
> benchmarks: only log the spammy iterations completed message if -v is set

- basic_test.go
- benchmarks/bench_test.go
- benchmarks/cosmos-exim/main.go
- cmd/iaviewer/main.go
- export_test.go
- immutable_tree.go
- import_test.go
- iterator_test.go
- mutable_tree.go
- mutable_tree_test.go
- nodedb_test.go
- proof_iavl_test.go
- proof_ics23_test.go
- testutils_test.go
- tree_random_test.go
- tree_test.go
```go
type MutableTree struct {
*ImmutableTree                                     // The current, working tree.
lastSaved                *ImmutableTree            // The most recently saved tree.
orphans                  map[string]int64          // Nodes removed by changes to working tree.
versions                 map[int64]bool            // The previous, saved versions of the tree.
allRootLoaded            bool                      // Whether all roots are loaded or not(by LazyLoadVersion)
unsavedFastNodeAdditions map[string]*fastnode.Node // FastNodes that have not yet been saved to disk
unsavedFastNodeRemovals  map[string]interface{}    // FastNodes that have not yet been removed from disk
ndb                      *nodeDB
skipFastStorageUpgrade   bool // If true, the tree will work …
```
> feat: Add `skipFastStorageUpgrade` to `MutableTree` to control fast storage upgrade

- .github/workflows/ci.yml
- mutable_tree_test.go
Adding 3 simple tests that will fail if any new change makes the current situation with concurrency worse. These 3 always fail if the fast node is enabled (can be passed to `setupMutableTree`).
> feat: add iterator concurrency tests

- mutable_tree.go
Skip fast node removals when fast node is disabled to avoid any possibility of those removals being read, leading to inconsistent state between nodes that have fast nodes and the nodes that do not.
> refactor: disable remaining fast node logic in mutable tree

- immutable_tree.go
- import.go
- mutable_tree.go
- node.go
- node_test.go
- nodedb.go
- testutils_test.go
> feat: add nodeKey integer field

- immutable_tree.go
> fix: add field to struct

- internal/encoding/encoding.go
- node.go
- node_test.go
- remove the buffer when compute node hash
- benchmark different ways to hash node
```
$ go test -run=^$ -bench=BenchmarkNode_HashNode -benchmem ./ -count=5
goos: darwin
goarch: amd64
pkg: github.com/cosmos/iavl
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkNode_HashNode/NoBuffer-12         	 1571757	       757.0 ns/op	     160 B/op	       2 allocs/op
BenchmarkNode_HashNode/NoBuffer-12         	 1594012	       751.8 ns/op	     160 B/op	       2 allocs/op
BenchmarkNode_HashNode/NoBuffer-12         	 1598257	       757.4 ns/op	     160 B/op	       2 allocs/op
BenchmarkNode_HashNode/NoBuffer-12         	 1578457	       745.4 ns/op	     160 B/op	       2 allocs/op
BenchmarkNode_HashNode/NoBuffer-12         	 1613202	       783.7 ns/op	     160 B/op	       2 allocs/op …
```
> optim: remove the buffer when compute node hash

- go.mod
- go.sum
- proof_ics23.go
- proof_ics23_test.go
I was trying to use cosmos/iavl in some benchmark tests for cosmos/ics23 and got some mismatch type errors (iavl returning a type from confio/ics23 but ics23 expecting a type from cosmos/ics23), so I thought the dependency could be updated here then.
> deps: replace confio/ics23 with cosmos/ics23

- CHANGELOG.md
- diff_test.go
- mutable_tree.go
ref: #675 
To migrate the original tree to the new node-key, it needs to sync the specific version in the new format
> feat: add api to save `ChangeSet`

- diff.go
- import.go
- iterator.go
- iterator_test.go
- mutable_tree.go
- mutable_tree_test.go
- node.go
- node_test.go
- nodedb.go
- nodedb_test.go
- tree_test.go
ref: #747 
It refactored the node struct as discussed in #747.
`leftNodeKey` and `rightNodeKey` types are changed from `*NodeKey` to `[]byte` to allow the reference of the old key format (node hash).
> feat: refactor the node struct

- .github/workflows/benchmarks.yml
- .github/workflows/ci.yml
- benchmarks/bench_test.go
- cache/cache.go
- cmd/iaviewer/main.go
- go.mod
- internal/bytes/string.go
- internal/rand/random_test.go
- mutable_tree.go
- nodedb.go
- proof_ics23_test.go
- tree_dotgraph.go
- unsaved_fast_iterator.go
The safer functions require Go 1.20. Let me know if that's not acceptable.
CC @odeke-em
> perf: reduce use of unsafe functions, and make them safer

- README.md
- VERSIONS.md
I have every time to lookup which versions are compatible with which IAVL version and tm-db/cometbft-db/cosmos-db version.
This adds a table, so we do not need to look it up all the time.
Feel free to close it if we do not need to add this to the repo, at least now I still have this PR to refer myself to.
> docs: add cosmos sdk compatibility table

- CHANGELOG.md
- mutable_tree.go
I think the optimistic execution and async commit in sdk will need this together with the `WorkingHash` API.
hide the initial version logic inside.
useful in [async commit](https://github.com/cosmos/cosmos-sdk/pull/16175), will be useful in optimistic execution.
> feat: add `WorkingVersion` API

- CHANGELOG.md
- import.go
- nodedb.go
Closes: #772 
don't need to reference the children, which recursively retain the whole subtree in memory.
> fix: memory leak in `Import`

- CHANGELOG.md
- import.go
don't reference the children, which recursively retain the whole subtree in memory.
> fix: memory leak in `Import` (backport #773)

- README.md
Ensuring that old discord links are up to date for security purposes.
> docs: replace dead links in README.md

- .golangci.yml
- CHANGELOG.md
- basic_test.go
- diff_test.go
- immutable_tree.go
- nodedb.go
- tree_random_test.go
for more info, see https://github.com/cosmos/iavl/pull/654
> feat: Add API `TraverseStateChanges` to extract state changes from iavl versions (backport: #654) 

- .mergify.yaml
- README.md
- export_test.go
- go.mod
The v0.21 line is unused and should be retracted to avoid maintenance burden and confusion about releases.
- https://sourcegraph.com/search?q=context%3Aglobal+iavl+v0.21&patternType=standard&sm=1&groupBy=repo
Both results indicate that the indirect dependency on v0.21 is replaced by respectively v0.20.0 and v0.19.4 in the go.mod.
> chore: retract v0.21.x line

- batch.go
- batch_test.go
- mutable_tree_test.go
- nodedb.go
- nodedb_test.go
This PR replace the use of normal dbm.Batch with BatchWithFlusher in iavl tree
It also hard code the value of flushthreshold to 100KB
> feat: Uses BatchWithFlusher in iavl tree

- CHANGELOG.md
- batch.go
- batch_test.go
- benchmarks/bench_test.go
- immutable_tree.go
- iterator_test.go
- mutable_tree.go
- mutable_tree_test.go
- nodedb.go
- nodedb_test.go
- options.go
- proof_iavl_test.go
- testutils_test.go
- tree_random_test.go
- tree_test.go
follow up to https://github.com/cosmos/iavl/pull/807
> refactor: make batcher configurable

- iterator_test.go
- mutable_tree.go
- unsaved_fast_iterator.go
cref: https://github.com/cosmos/iavl/issues/696
This PR fixes the problem stated above by replacing maps that causes racing conditions to sync map to be thread safe. 
Tested this on various chains' nodes that's having concurrency issue by applying patch manually, confirmed that after applying this patch concurrency issue is not happening any more. (special shout out to @keplr-wallet for helping out testing!)
Also confirmed and tested on a testnet node with the following procedure:
- Have node running 
- Spam it with tx bots and query bots
- Previously node would crash within 1, maximum 2 minutes with the racing condition logs mentioned above
> feat: Support concurrency for IAVL and fix Racing conditions

- iterator_test.go
- mutable_tree.go
- unsaved_fast_iterator.go
Backporting https://github.com/cosmos/iavl/pull/805 so that we can have a minor release for existing releases
> chore: Backport IAVL Concurrency fix for v0.19

- nodedb.go
- nodedb_test.go
Noticed during an audit that there can be a deadlock resulting from an unreleased mutex if there happens to be a newer version with one or more concurrent readers.
Fixes #842
> fix(nodedb): prevent deadlock by releasing DeleteVersionsFrom mutex on error

- export.go
- multitree.go
- snapshot.go
- tree.go
- tree_test.go
> feat: add post-order export & restoring

- mutable_tree.go
In previous iavl, the version is not affecting to working hash. but in current iavl, the version is a part of working hash, so the `InitialVersion` should be used when you make working hash at newly added moules. 
https://github.com/cosmos/iavl/blob/af7ae13f47a477f11c18a4856d4a0c4e4a344e45/node.go#L435
The problem is happening when you adding an new module [`packetforward`](https://github.com/cosmos/ibc-apps/tree/main/middleware/packet-forward-middleware), you can easily reproduce the consensus breaking with software upgrade proposal. You should run more than two nodes and after upgrade restart validator node and see other nodes.
We deeply debugged it and found the working hash for the stores, which are added via upgrade, are same whatever the height you did upgrade (` [164 128 39 101 194 …
> fix: pass initial version at immutable tree creation

- .github/workflows/lint.yml
- CHANGELOG.md
- batch.go
- fastnode/fast_node.go
- go.mod
- internal/encoding/encoding.go
- keyformat/prefix_formatter.go
- mutable_tree.go
- node.go
- nodedb.go
This feature prevents the multiple hour long waiting period when chains upgrade from previous versions of IAVL to IAVL v1. The time comes from pruning orphan nodes. This synchronously prunes them. This branch has been tested successfully against osmosis mainnet.
> feat(v1.x.x): async pruning of orphan nodes

- node.go
We cannot assume the `leftNodeKey` and `rigthNodeKey` is finalized at the hash calculation stage, they will be re-assigned in `saveNewNodes`. IAVL V1 doesn’t ensure leftNodeKey and rightNodeKey updates when rotating, only update leftNode and rightNode relations in-memory, and children nodeKey will be resolved at the commit stage.
> fix: revert the children node key refer

- cache/cache.go
This change brings back an optimization that go innocently removed while trying to reduce the number of invocations to node.GetKey() in PR #890.
The Go compiler considers the special case of lookups per:
value, ok := map[string(byteslice)]
or
value := map[string(byteslice)]
and performs a zero byteslice->string conversion because it knows that there is no storing in the map hence a read-only usage of the byteslice's memory.
> perf: fix accidentally undone Go map[string(byteslice)] lookup optimization

- CHANGELOG.md
- batch.go
- import.go
- migrate_test.go
- mutable_tree.go
- node.go
- nodedb.go
- nodedb_test.go
- tree_test.go
> chore: backport the pruning fix PR to v1.1.x

- internal/encoding/bench_test.go
- internal/encoding/encoding.go
This change speeds up EncodeVarint by testing if the input writer implements io.ByteWriter and if so, goes to use our hand-rolled varint encoder, instead of using the awkward standard libary encoding/binary.PutVarint that requires a byteslice, which we also retrofitted using a bytearray pool.
While here, added parity tests to ensure that we get the exact same results as with the Go standard library's encoding/binary package with caution from https://cyber.orijtech.com/advisory/varint-decode-limitless and also added benchmarks whose results reflect the change in just the benchmark initially
```shell
$ benchstat before.txt after.txt
name            old time/op    new time/op    delta
EncodeVarint-8     360ns ± 3%     245ns ± 3%  -31.80%  (p=0.000 n=10+10)
name            old alloc/op   new …
```
> perf(encoding): speed up EncodeVarint with io.ByteWriter+hand rolled varintEncode

- mutable_tree.go
- mutable_tree_test.go
- nodedb.go
There are some unnecessary `ndb.Commit` and `resetBatch` calls which introduced to avoid the large batch commit originally. They are not necessary since we are using `BatchWithFlusher` now.
> chore: cleanup unnecessary `ndb.Commit` calls

- CHANGELOG.md
- mutable_tree.go
- tree_test.go
After reformatting of the pruned root node, it may be referred as a legacy node, since the nonce is 0.
> fix: legacy node key

- CHANGELOG.md
- migrate_test.go
- mutable_tree.go
- nodedb.go
- options.go
- prune_test.go
Closes: #885 
Added the `AsyncPruning` option, it needs to call `SetCommitting` and `UnsetCommitting` when committing in the store module in the async pruning mode.
It doesn't break the original APIs.
> feat: deferred pruning

- CHANGELOG.md
- mutable_tree.go
- tree_test.go
`InitialVersion` is not reflected in the `WorkingHash` calculation, only reflected in the `SaveVersion`. This will lead to the `AppHash` mismatch while upgrading, since the the hash of the root is already calculated in the `WorkingHash` and won't re-calculated in the `SaveVersion` which is wrong.
> fix: working hash with initial version

- import.go
- import_test.go
context [here](https://github.com/cosmos/cosmos-sdk/issues/23740)
and this PR replace https://github.com/cosmos/iavl/pull/1050
`release/v1.3.x` should also be backported
> fix: batch write race on commit (backport #983) (#992)
