cosmos/iavl

iavl_proof_key.go
iavl_proof_key_test.go
iavl_test.go

We need to have solid binary reader and writers for the proofs.  At least the key proofs for now, until we expose more to the outside worlds.

Serialize proofs

---

glide.lock
glide.yaml
nodedb.go

This implementation is done but the tests won't pass until we complete and merge tmlibs@sdk2-iterator

WIP: Sdk2 iterator

---

benchmarks/bench_test.go
benchmarks/hash_test.go

Improve benchmarks, target sdk2 code

Sdk2 benchmarks

---

node.go
proof.go
sha256truncated/sha256truncated.go
sha256truncated/sha256truncated_test.go

Change from RIPEMD160 to SHA256
resolves #38 
If #53 is merged we can additionally remove ripemd160 from the glide file (or dep file if #52 get's merged first)

Minimal changes to resolve #38

---

CHANGELOG.md
version.go

Just writing up what differs on develop compared to master as is. Currently it's just this.

update changelog and version

---

CHANGELOG.md
version.go

- bump version
- update changelog
Signed-off-by: Liamsi <Liamsi@users.noreply.github.com>

release v0.9.2

---

CHANGELOG.md
version.go

- update changelog and bump versions

release v0.12.2

---

Makefile
node.go
util.go

- Colors.go was removed from tendermint

Remove use of colors

---

CHANGELOG_PENDING.md

- Increase amount of contributions to this repo brings the need of a changelog_pending file.

Add ChangeLog_Pending

---

.golangci.yml
common/bytes.go
common/bytes_test.go
common/mutate.go
common/random.go
common/random_test.go
nodedb.go
nodedb_test.go
proof.go
proof_range.go
proof_test.go
testutils_test.go
tree_fuzz_test.go
tree_test.go

- Reason: tm-cmn has been decided to become tm-db, to solely hold the db functionality.
- also did some minor linting cleanup

Move used common files to repo

---

CHANGELOG.md
CHANGELOG_PENDING.md
go.mod
go.sum

- this release will only hold changes made to cmn and db
- we want to encourage people to use releases instead of master.

Minor release

---

CHANGELOG_PENDING.md

Add a changelog entry for fix

---

mutable_tree.go
mutable_tree_test.go
nodedb.go
pruning_test.go

tm-db 0.4.0 introduced more returns with errors, bubbling up more errors because of this.

errors: add some error handling

---

cmd/iaviewer/README.md

A fancy-sounding commit title for a tiny change.

cmd/iaviewer: update docs for modules

---

CHANGELOG.md

Not sure how to make the actual release. No rush, this can totally wait until Monday.

Release v0.13.1

---

README.md
go.mod
go.sum

bump required go version and add test & lint badges

Go version

---

.github/workflows/lint.yml
.golangci.yml
benchmarks/bench_test.go
go.mod
go.sum
node.go
proof_path.go
proof_test.go

- change linter in ci
- enable nolintlint

ci: change to official linter

---

proof.go
proof_range.go

Code tweaks split out from #217. Mostly additional comments and variable renaming.

proof: clarify and tweak code

---

docs/architecture/README.md
docs/architecture/adr-001-flush-version.md
docs/architecture/adr-template.md

references:
- https://github.com/tendermint/iavl/pull/239

ADR 001 - Flush Version

---

CHANGELOG.md
Makefile
README.md
benchmarks/README.md
benchmarks/bench_test.go
benchmarks/cosmos-exim/main.go
benchmarks/hash_test.go
benchmarks/setup/RUN_BENCHMARKS.sh
cmd/iaviewer/README.md
cmd/iaviewer/main.go
doc.go
docs/proof/proof.md
go.mod
proof.go
proof_test.go
testutils_test.go
tree_fuzz_test.go
tree_test.go

update module path to github.com/cosmos/iavl

---

tree_random_test.go

Checks that we don't leave behind any junk in the database, as reported in #324.

test: check stray database entries in TestRandomOperations

---

CHANGELOG.md
mutable_tree.go
mutable_tree_test.go
nodedb.go
tree_random_test.go
tree_test.go

Ports a bugfix and new method from the 0.14.x branch (#324), and some added tests.

port DeleteVersions and DeleteVersionsRange

---

.github/workflows/docker.yml

- push docker images
closes #311

docker: ci

---

CHANGELOG.md
proof_path.go

remove unnecessary empty lines in PathToLeaf.String()

---

CHANGELOG.md

Requested in https://github.com/cosmos/iavl/pull/352#issuecomment-748586579.

changelog: release 0.15.3

---

.github/CODEOWNERS

Is there anyone else who should be on here @robert-zaremba? Also, you may need to get added to the `regen_iavl_maintain` team for commit access.

github: update CODEOWNERS with Regen maintainers

---

encoding.go

By using a sync.Pool to shared temporary buffer between calls.
While at it, also using plain sync.Pool.Put instead of using defer, save
us a little time, and without affecting the readability of the code.
```
name                             old time/op    new time/op    delta
Export-8                           7.83ms ± 1%    7.86ms ± 1%     ~     (p=0.247 n=10+10)
Import-8                           8.90ms ± 0%    8.95ms ± 0%   +0.59%  (p=0.003 n=9+9)
Node_WriteBytes/NoPreAllocate-8     232ns ± 0%     227ns ± 0%   -2.47%  (p=0.000 n=9+10)
Node_WriteBytes/PreAllocate-8       204ns ± 1%     197ns ± 0%   -3.26%  (p=0.000 n=9+10)
name                             old alloc/op   new alloc/op   delta
Export-8                           3.74MB ± 0%    3.74MB ± 0%     ~     (p=0.589 n=10+9) …
```

Reduce encodeUVarint memory usage

---

CHANGELOG.md

changelog update for v0.17.1 release

chore: changelog update for v0.17.1 release

---

nodedb.go
options.go
tree_test.go

For a better user experience, add optional statistics for cache miss rate.

add Statistics for cache miss rate

---

LICENSE

Closes: #522 
Related to: https://github.com/cosmos/cosmos-sdk/pull/12542

chore: update license copyright

---

nodedb.go
options.go

https://github.com/cosmos/iavl/issues/507

refactor: Statistics check for nil in its methods

---

CHANGELOG.md

chore: prepare for release

---

benchmarks/cosmos-exim/main.go
cache/cache.go
doc.go
fast_node.go
immutable_tree.go
iterator.go
key_format.go
node.go
nodedb.go
proof.go
proof_range.go

This fixes linting issues exposed by running the linter in #535

linting fixes

---

benchmarks/bench_test.go

To ensure that benchmarks run smoothly by default even if the tags "-tags=cleveldb,rocksdb" are missing, just log errors that result from missing runtime linked databases.
Fixes #549

benchmarks: on missing/unlinked DB -tags=cleveldb,rocksdb, just log errors instead of failing

---

Makefile
go.mod
go.sum
mutable_tree.go
proof_iavl_absence.go
proof_iavl_value.go
proof_test.go
proto/proof.pb.go

- migrate to `cosmos/gogoproto`
- add `make lint-fix` and run it

refactor: migrate to cosmos/gogoproto

---

.github/workflows/lint-pr.yml

Adds lint-pr action. This forces the standardization of PR titles.

ci: add lint PR action

---

.golangci.yml
cmd/iaviewer/main.go
export.go
immutable_tree.go
mutable_tree.go
mutable_tree_test.go
nodedb.go
proof_range.go
tree_dotgraph.go
util.go

This PR:
* removes deprecated linters
* does a linting pass

chore: don't use deprecated linters

---

.golangci.yml
basic_test.go
benchmarks/bench_test.go
cache/cache_test.go
export_test.go
immutable_tree.go
import_test.go
internal/bytes/string_test.go
mutable_tree.go
mutable_tree_test.go
nodedb.go
nodedb_test.go
proof_iavl_test.go
proof_ics23_test.go
proof_test.go
tree_dotgraph_test.go
tree_random_test.go
tree_test.go

chore: lint iavl

---

diff.go
iterator.go
nodedb.go

it's being running on our testnet, ~~not finished yet~~, but so far so good, the result is identical to previous version.
EDIT: the task previously takes 19hours to run, now takes 14h20m, not bad.

perf: Optimize diff algorithm with insights from #646

---

.mergify.yaml

chore: fix mergify

---

iterator.go

fix unit test failure, it's a mistake in back-porting https://github.com/cosmos/iavl/pull/665

fix traverse order in tree iterator

---

docs/node/key_format.md
docs/node/node.md
docs/node/nodedb.md

docs: Minor cleanup

---

.github/workflows/lint.yml
Makefile
mutable_tree.go
nodedb.go
tree_test.go

fix: empty root loading failed

---

internal/color/colors.go
node.go
util.go

Though tbh, can we just delete this? Pretty crazy this in our DB code?

refactor!: Move color to its own package

---

internal/rand/random.go
keyformat/key_format.go
nodedb.go
nodedb_test.go

Low priority cleanups noticed during code review.
CC @odeke-em

chore: various cleanups

---

tree_dotgraph.go

chore: remove TODO

---

.golangci.yml
basic_test.go
tree_dotgraph_test.go
tree_random_test.go
tree_test.go

style: adjust for existing lint error

---

CHANGELOG.md
immutable_tree.go
iterator_test.go
mutable_tree.go
nodedb.go
nodedb_test.go
tree_random_test.go

API consistency for https://github.com/cosmos/iavl/pull/815

refactor: api consitency

---

mutable_tree.go
nodedb.go

ref: https://github.com/cosmos/cosmos-sdk/actions/runs/6169951960/job/16745260048?pr=17693

fix: data race of latestVersion

---

docs/node/nodedb.md
docs/proof/proof.md
docs/tree/mutable_tree.md

Came across few typos while reading the docs, hope I could be of any help!

chore: docs proofreading

---

CHANGELOG.md

chore: changelog v1

---

node.go

fix: revert the children node key refer

---

mutable_tree.go

ref: https://github.com/cosmos/iavl/pull/910#issuecomment-1996326187

fix(v1.x.x): revert unnecessary changes

---

CHANGELOG.md
nodedb.go
nodedb_test.go

Resolves #1017
I have tested this via SDK sims.

fix: Better lock handling on close
